name: Build master

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1

    # - uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: '5.0.x'
    # # Not specifying a version will attempt to install via global.json
    # - name: Use .NET Core global.json
    #   uses: actions/setup-dotnet@v1
    - run: 'dir env:'
    #- run: dotnet --version
    #- run: dotnet --list-sdks
    #- run: dotnet tool restore
    - name: Build
      if: runner.os == 'Windows'
      run: 'msbuild "Map Loader.sln"'
      env:
        CI: true
